<?php

/**
 * @file
 * Install, update and uninstall functions for the Geocoder module.
 */

/**
 * Implements hook_schema().
 */
function geocoder_schema() {
  $schema['cache_geocoder'] = drupal_get_schema_unprocessed('system', 'cache');
  $schema['cache_geocoder']['description'] = 'Cache table for the geocoder module to store geocoded locations.';

  return $schema;
}

/**
 * Create geocoder's caching table.
 */
function geocoder_update_7101() {
  drupal_install_schema('geocoder');
}
